// The example story, verbatim from the HeresThe.News edition of August 3, 2026,
// marked up the same way the live site renders it.
const STORY_HTML = `
<article class="story-card">
  <p class="kicker">Weather · Monday, August 3</p>
  <h3 class="headline">Wildfires destroy more than 600 structures near Spokane, Washington</h3>
  <div class="sum-meta"><span class="chip status-developing">developing</span></div>
  <div class="impact-wrap"><p class="impact"><span class="impact-label">Why it matters</span>More than 600 homes, businesses and other buildings near Spokane have burned, and evacuation orders were still in place as of Sunday. Outlets differ on the scale of the evacuation: two report about 5,000 homes, one reports about 60,000 people. The fires were 0% contained as of Sunday, August 2.</p></div>
  <p class="facts-head">The facts <span class="fcount fc-v"><i>●</i>3 verified</span><span class="fcount"><i>○</i>1 reported</span><span class="fcount fc-d"><i>◐</i>1 disputed</span></p>
  <ul class="facts">
    <li class="fact"><span class="chip status-verified">verified</span><span class="fact-text">Wildfires around Spokane, Washington - the Old Trails, Autumn Lane and Fairview fires, together called the Spokane Area Fires - have destroyed more than 600 homes, businesses and other buildings.<span class="corr">— CBS News, PBS NewsHour, Washington Times and KHQ (citing InciWeb / California Interagency Incident Management Team 7) all report roughly 600-640 structures destroyed</span></span></li>
    <li class="fact"><span class="chip status-reported">reported</span><span class="fact-text">The fires had burned about 5,390 acres (8.4 square miles) as of Sunday morning, August 2, per InciWeb; CBS News reported the burned area at about 12 square miles by Sunday evening.<span class="corr">— InciWeb figure via KHQ for the Sunday-morning count; CBS News for the Sunday-evening count. The fire was growing between the two snapshots, so the difference reflects timing, not conflicting counts.</span></span></li>
    <li class="fact"><span class="chip status-disputed">disputed</span><span class="fact-text">Evacuation figures differ by outlet: PBS NewsHour and the Washington Times reported about 5,000 homes evacuated, while CBS News reported about 60,000 people evacuated, quoting Spokane Mayor Lisa Brown.<span class="corr">— PBS NewsHour and Washington Times: ~5,000 homes; CBS News: ~60,000 people. The two figures use different units and no outlet reconciled them.</span></span></li>
    <li class="fact"><span class="chip status-verified">verified</span><span class="fact-text">Washington Governor Bob Ferguson declared a state of emergency on Saturday, August 1.<span class="corr">— Reported independently by CBS News and the Washington Times</span></span></li>
    <li class="fact"><span class="chip status-verified">verified</span><span class="fact-text">As of Sunday, August 2, the fires were 0% contained and no deaths had been confirmed. Spokane Mayor Lisa Brown said officials were still assessing the potential for lives lost.<span class="corr">— CBS News, PBS NewsHour and Washington Times all report no confirmed deaths and no containment as of Sunday; CBS quotes Mayor Brown directly</span></span></li>
  </ul>
  <p class="srcs-head">Read the full coverage</p>
  <p class="source-links"><span class="src"><a href="https://www.cbsnews.com/news/spokane-washington-wildfire-evacuations-old-trails-fire/" target="_blank" rel="noopener">CBS News</a><span class="lean-tag">center</span></span><span class="src"><a href="https://www.pbs.org/newshour/nation/eastern-washington-fires-have-burned-600-structures-and-forced-the-evacuation-of-5000-homes" target="_blank" rel="noopener">PBS NewsHour</a><span class="lean-tag">leans left-center</span></span><span class="src"><a href="https://www.washingtontimes.com/news/2026/aug/2/eastern-washington-fires-burned-600-structures-forced-evacuation-5000/" target="_blank" rel="noopener">Washington Times</a><span class="lean-tag">leans right</span></span><span class="src"><a href="https://www.khq.com/fires/evacuations-expanded-for-spokane-area-fires-burning-5-390-acres-600-structures-destroyed/article_8f1a90ab-1bb3-4fb7-8b6a-8464137bd373.html" target="_blank" rel="noopener">KHQ (citing InciWeb)</a></span></p>
</article>`;
